spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce_db
    username: ecommerce
    password: ecommerce123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: yourpassword